version: "3.8"
services:
  app:
    container_name: app
    restart: always
    image: ${winniebot_image}$
    depends_on:
      - postgres
    environment:
      - BOT_TOKEN=${botToken}$
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${pgUser}$
      - POSTGRES_PASSWORD=${pgPass}$
      - POSTGRES_DB=${pgDB}$