version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: ../.env
  redis:
    container_name: redis
    image: redis
    command: redis-server --requirepass winnie_redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/var/lib/redis
