name: Build Bot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install pnpm
      uses: pnpm/action-setup@v2.1.0
      with:
        version: latest
    - name: Install dependencies
      run: pnpm install
    - name: Run lint
      run: pnpm lint
    - name: Run TypeScript check
      run: pnpm build
