name: Release Bot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}
    - name: Build tfvars file
      run: cd ./terraform && printf "do_token = \"%s\"" $DO_TOKEN > cd.auto.tfvars
      env:
        DO_TOKEN: ${{ secrets.DO_PAT }}
    - name: Run terraform
      run: cd ./terraform && terraform init && terraform plan && terraform apply -auto-approve
    - name: Save droplet IP address as env var
      id: ip
      run: |
        cd ./terraform
        echo "::set-output name=ip::$(terraform output droplet-ip-address)"
    - name: Print IP address
      run: echo ${{ steps.ip.outputs.ip }}
    - name: Save private database connection string as env var
      run: cd ./terraform && echo DB_CONNECTION_STRING=$(terraform output database-connection-uri) >> $GITHUB_ENV
    - name: Clone, install deps, and start Winnie
      uses: appleboy/ssh-action@master
      with:
        host: ${{ steps.ip.outputs.ip }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          git clone git@github.com:aigeroni/Winnie_Bot
          yarn install
          yarn build
          yarn start
