const PROMPT_LIST = [
  'One of your characters receives an anonymous gift.',
  'Your character invites someone they don’t like over for dinner.',
  'A character is scared that someone will find out about something' +
            ' they did.',
  'Your character goes to the other side of town for a day.',
  'Two characters get into a heated argument about work.',
  'A character suddenly has to travel a long distance.',
  'Your character makes a new friend in an unexpected place.',
  'Your characters get dressed up.',
  'One of your characters isn’t who they claim to be.',
  'Your character is presented with a meal they don’t like.',
  'The scenery suddenly changes.',
  'An inanimate object moves.',
  'Your character turns off the music.',
  'Two things are unexpectedly related.',
  'The lights go out.',
  'Choose an object you can see; write it into your story.',
  'Today’s headlines make an announcement that is important to your' +
            ' character.',
  'Your character tries something wild.',
  'A character tells a lie.',
  'The right thing is there for your character, but at the wrong time.',
  'Your character has a skill that has not been mentioned before.',
  'A character breaks a rule.',
  'A character is late.',
  'Someone is injured.',
  'Mars is bright tonight.',
  'Something doesn’t work as it’s supposed to.',
  'A character loses something, but then finds or gets it back.',
  'A character changes careers.',
  'Start and end a paragraph with the same sentence, but give it different' +
        ' meanings.',
  'A character goes for a walk and discovers something strange.',
  'A character gets into a fight.',
  'Something has gone horribly wrong.',
  'A character misses something important.',
  'A character leaves their comfort zone.',
  'A character loses someone.',
  'A character passes out.',
  'A character hallucinates.',
  'A character leaves home for the last time.',
  'Someone is searching for something.',
  'A character forgets something important.',
  'A character is angry at someone they feel is more powerful than them.',
  'It starts to rain.',
  'Someone unexpected arrives.',
  'A character notices someone watching them.',
  'A crowd has gathered.',
  'Something has a dual function.',
  'The only useful thing is in the corner.',
  'Your character cracks a bad joke.',
];

exports.PROMPT_LIST = PROMPT_LIST;
